<?php

namespace NL\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('a')
            ->join('a.categories','c')
            ->addSelect('c')
        ;

        // Puis on filtre sur le nom des catégories à l'aide d'un IN
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }


    public function getAdverts()
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.categories','c') // Jointure sur l'attribut categories
            ->addSelect('c')
            ->leftJoin('a.image','i')      // Jointure sur l'attribut image
            ->addSelect('i')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
        ;

        return $qb->getResult();
    }
}
