<?php

namespace NL\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('app')
            ->join('app.advert', 'a')
            ->addSelect('a')
            ->setMaxResults('$limit') // On ne retourne que $limit résultats
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
