nl_platform:
    resource: "@NLPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    pattern: /login
    defaults: { _controller: NLUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
