parameters:
    nb_per_page: 2

services:
    nl_platform.antispam:
        class: NL\PlatformBundle\Antispam\NLAntispam
        arguments: [@mailer, %locale%, 50]

    nl_platform.doctrine.notification:
        class: NL\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    nl_platform.validator.antiflood:
        class: NL\PlatformBundle\Validator\AntifloodValidator
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: nl_platform_antiflood }